version: "3.8"

services:

#  proxy:
#    image: jwilder/nginx-proxy
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#    ports:
#      - "80:80"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kosmopoisk
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - mysqldb:/var/lib/mysql

  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
#    environment:
#      VIRTUAL_HOST: kosmopoisk.test

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
#    environment:
#      VIRTUAL_HOST: adminer.test

volumes:
  mysqldb:
